# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=8)),
                ('account_pass', models.CharField(max_length=16)),
                ('account_email', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.IntegerField(default=67)),
                ('photo_photo', models.CharField(default='', max_length=1024)),
                ('photo_account_id', models.CharField(max_length=8)),
            ],
        ),
    ]
